### PR TITLE
Add copy to clipboard button for snippet files

### PR DESCRIPTION
**Pull request by nezhar**
Implements #32
Adds a copy button which helps copy files from the snippet directly to the clipboard.

### CODE REVIEW

**Comment by sterapps** [comment]
Please fix lint errors.

**Comment by nezhar** [comment]
> Please fix lint errors.

fixed :wink:

**Comment by sterapps** [comment]
It would be nice to show a toast message when file successfully copied to improve user experience. What do you mean?

**Comment by nezhar** [comment]
> It would be nice to show a toast message when file successfully copied to improve user experience. What do you mean?

This souds good. I would suggest that the button changes from `copy` to `coppied` when clicked, and from class `primary` to `success` and is disabled for a few secconds. I will try to adapt this, as the PR also needs to be rebased.

**Comment by nezhar** [comment]
@sterapps I added the button as described above.

**Review by sterapps — APPROVED** [review]

**Pull request merged**
